datavzrd/datavzrd

README.md, src/render/portable/mod.rs, src/render/portable/plot.rs, src/spec.rs, templates/table.js.tera, templates/tick_plot.vl.tera
This PR adds tick plots that can be rendered to individual columns with the new keyword `plot` followed by `ticks`.
=> feat: Add tick plots

README.md
This PR links [koesterlab/yte](https://github.com/koesterlab/yte) from the README.md
=> docs: Add yte to README.md

.examples/data/movies.csv, .examples/data/oscars.csv, .examples/example-config.yaml, .github/workflows/example-report.yml, README.md
This PR adds an example report that is linked to from the README.md to the repository that will be regenerated on every push to the `main` branch.
=> feat: Add example report

src/main.rs
This PR add an error message for a wrong config file path.
=> fix: Complete error message for wrong config file path

src/render/portable/mod.rs, src/render/portable/plot.rs, src/spec.rs
This PR add a proper error message to datavzrd for non existing file paths for csv files.
=> feat: Show proper error message for wrong file paths

src/main.rs
This PR shows proper error messages for non existing output directories.
=> feat: Show proper error message for non existing output directory

templates/plot.html.tera, templates/search_dialog.html.tera, templates/table.html.tera
Just a few tweaks and fixes regarding the cosmetics of the reports.
=> fix: Minor cosmetic changes

src/render/portable/mod.rs, templates/empty.html.tera
This PR fixes #35. Instead of an error, a page is generated that simply dislplays `No data`.
=> fix: No error for empty csv files

README.md
This PR adds the possible values to the documentation of the keyword `display-mode`.
=> docs: Add possible values for display-mode

templates/table.js.tera
This PR fixes #33 by adjusting the header height to the content.
=> fix: Adjust header height to content

templates/table.js.tera
This PR removes the ellipsis from datavzrd due to some problems. It'll be reintroduced in a different way in a later version.
=> fix: Remove ellipsis from datavzrd

src/render/portable/mod.rs
This PR improves the error message for non existing columns that are not marked with `optional: true`.
=> fix: Improve error message for missing columns without optional: true

.examples/data/oscars.csv, .examples/example-config.yaml, src/spec.rs
This PR adds a testcase for the preprocessing of the config file.
=> test: Add test for config preprocessing

templates/table.js.tera
Custom plots were not working in detail view. This PR makes them render in detail view too.
=> fix: Show custom plots in detail view

templates/table.html.tera
This PR removes the highlighting on hover from datavzrd.
=> feat: Remove hovering from table

Cargo.lock, Cargo.toml, src/render/portable/utils.rs, tests/expected/index.html
This PR adds test coverage for all utils of the portable mod.
=> test: Fully test portable utils

templates/tick_plot.vl.tera
This PR resizes plots generated with `ticks` to save some space.
=> feat: Resize tick plots

static/datavzrd.css, templates/linkout_button.html.tera
This PR re-styles and resizes the linkout buttons.
=> feat: Resize linkout buttons

src/spec.rs
This PR lets the validate function check if the config contains valid values for the scale-types of `ticks` and `heatmap`.
=> feat: Validate plot scale types

static/datavzrd.css, templates/table.html.tera, templates/table.js.tera
=> feat: Style table

src/spec.rs
This PR adds validation to linkouts specified in `datasets`.
=> feat: Validate linkouts

src/spec.rs
This PR makes datavzrd validate the given default-view. Also some minor fixes for the tests are included in this PR
=> feat: Validate given default-view

src/main.rs, src/spec.rs
This PR fixes a problem with displaying errors from config validation.
=> fix: Show error messages from config validation properly

static/datavzrd.css, templates/table.js.tera
This PR improves the detail formatter so that it waists less space. This closes #136.
=> feat: Improve detail formatter

src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
This fixes the usage of `page-size` with single-page views.
=> fix: Fix usage of page-size for single page views

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/spec.rs, src/utils/column_index.rs, templates/table.js.tera
This PR adds the option to add heatmaps to additional header rows and therefore closes #169. This PR also fixes some problems with additional headers that came with single page views with js paging.
=> feat!: Add heatmap option for additional headers

README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
This PR adds a new keyword `precision` allowing users to set the precision of floats in the table. Therefore the closes #178.
=> feat: Add precision keyword for displaying numeric values

README.md, src/render/portable/mod.rs, src/spec.rs, static/datavzrd.css, templates/table.js.tera
This PR adds the option to label additional header rows and therefore closes #181.
=> feat: Add optional labeling for headers

.examples/specs/movies.vl.json, .examples/specs/oscars.vl.json, src/render/portable/mod.rs, src/spec.rs, static/datavzrd.css, templates/table.html.tera, templates/table.js.tera, templates/table_heatmap.js.tera, templates/table_heatmap.vl.tera
This PR addresses and closes #196 by implementing the export option described in the issue.
=> feat: Add ability to export whole table to vega-lite heatmap

templates/table.js.tera
This PR removes linkout data from the heatmap spec.
=> perf: Remove unused data field from heatmap spec

.examples/example-config.yaml, templates/table.js.tera
This PR makes precision work for non-scientific notation.
=> fix: Fix precision for non-scientific notation

src/spec.rs
This PR makes datavzrd validate the domains of given configs by checking if the values lie in between the boundaries. This therefore closes #255.
=> feat: Validate domains of plots

src/spec.rs
This PR makes datavzrd throw an error when a log scales domain includes 0 and therefore closes #256.
=> feat: Panic if log scale includes zero

static/datavzrd.css
A quick PR that fixes the row height and therefore closes #263.
=> fix: Fix row height

README.md
Just a quick PR to update the links after the organization change.
=> docs: Update README.md links

.github/workflows/release-please.yml
Another mandatory update for the ci so the release please action will run as expected.
=> ci: Update repository owner for release please

Cargo.lock, src/render/portable/mod.rs, src/render/portable/plot.rs
This PR fixes some slippy lints and updates the Cargo.lock file
=> refactor: Remove unnecessary borrows

src/spec.rs
This PR adds log scale value validation for bar-plots, ticks and heatmaps.
=> feat: Add log scale value validation for plots

src/render/portable/plot.rs
A quick PR implementing a lint from clippy keeping the code as clean as possible.
=> refactor: Fix clippy lint

src/render/portable/mod.rs, src/render/portable/plot.rs, src/spec.rs
A quick PR that applies the latest lints from clippy.
=> refactor: Apply latest clippy lints

src/cli.rs, src/main.rs
This PR implements and therefore closes #329.
=> feat: Add --overwrite-output option

src/render/portable/mod.rs
=> fix: Improve context when calculating links between datasets

static/datavzrd.js
This PR shows an ellipsis as tooltip and therefore also fixes #330.
=> fix: Show ellipsis as tooltip

templates/table.js.tera
This PR fixes custom plots on multi page views.
=> fix: Fix custom plots on multi page views

src/cli.rs, src/main.rs, src/render/mod.rs, src/render/portable/mod.rs, src/render/portable/plot.rs, src/render/portable/utils.rs
This PR adds a debug mode to datavzrd where js files are not minified for better identification of errors.
=> feat: Add debug mode

templates/table.js.tera
This PR fixes the rendering of header rows after manual or automatically triggered page changes.
=> fix: Fix rendering of header rows after page change

.github/workflows/apply-clippy-lints.yaml
This PR sets up the automatic fixing of clips lints using https://github.com/fxwiegand/apply-clippy-lints.
=> ci: Setup autofix for clippy lints

static/datavzrd.js
This PR fixes the newly introduced new-window keyword that didn't work properly for single links.
=> fix: Fix new-window keyword

.examples/data/oscars.csv, .examples/example-config.yaml, .examples/specs/overall-wins-and-overall-nominations.vl.json, src/spec.rs
This PR extends the dataset so the example reports contains a custom plot. Since this makes the example report use more features bugs will be easier to spot in the future and refactoring like #317 is much easier to test.
=> docs: Improve example report with custom plots

static/datavzrd.css
This PR fixes the table plot for wide tables that weren't scrollable before.
=> fix: Fix table plot for wide tables

static/datavzrd.js
This PR fixes a problem that occurred when refactoring most javascript in #397.
=> fix: Fix custom formatter

src/render/portable/mod.rs, src/spec.rs, static/datavzrd.css, templates/html.html.tera, templates/plot.html.tera, templates/table.html.tera
This PR makes datavzrd show the number of rows of the current table as a badge in the nav bar.
=> feat: Show number of rows in badge

src/render/portable/mod.rs, templates/empty.html.tera
This PR fixes the dropdown menu for empty table views.
=> fix: Fix dropdown of empty table view

src/render/portable/mod.rs
This PR adds more context to the current error message when there is a problem when vega for plots.
=> fix: Improve error message for JSON parsing error

static/datavzrd.css, templates/html.html.tera, templates/plot.html.tera, templates/table.html.tera, web/src/datavzrd.js
This PR optimizes the the new menu usage and changes the design a bit.
=> fix: Optimize new menu design and usage

web/src/datavzrd.js
This PR follows up on #497 and fixes the its function call.
=> fix: Fix embed search function call

.github/workflows/release-please.yml
This PR fixes the new web view update job.
=> ci: Fix update-webview job

.github/workflows/release-please.yml
This PR add some debug statements to the update webview workflow that should clear up the directory structure.
=> ci: Debug webview updating

templates/search_dialog.html.tera, web/src/datavzrd.js
This PR fixes another bug thankfully reported by @manuelphilip to me where the static search dialog wasn't fully functioning and was missing the input field.
=> fix: Fix static search dialog

.github/workflows/release-please.yml
This PR should fix the update webview workflow.
=> ci: Fix update webview job

web/src/datavzrd.js
A quick PR that fixes the rendering for reports with aux-domains.
=> fix: Fix rendering for reports with aux-domains

static/datavzrd.css, templates/plot.html.tera, templates/table.html.tera, web/src/datavzrd.js
This PR revises how datavzrd shows the description field.
=> feat: Show description by default with higher z-index and lower background opacity

.github/workflows/release-please.yml
This should fix the automatic updating of the web view since the generated deployment token only works for your user name @johanneskoester i suppose right?
If that doesn't work i would go with the route with the artifact as you suggested.
=> ci: Fix updating of view repository

.github/workflows/release-please.yml
Minor changes to the view update of the ci.
=> ci: Add datavzrd version to commit message of view update

static/datavzrd.css, web/src/datavzrd.js
This PR moves the filter mechanisms into popovers and therefore closes #552.
=> feat: Move filter mechanism into popover

web/src/datavzrd.js
This PR removes the potential risk of contents from newly added columns will be swapped.
=> fix: Fix potential wrong ordering of add-columns

src/render/portable/mod.rs
Just a quick PR doing some refactoring for the js config generation.
=> refactor: Use function to filter plot titles

src/render/portable/mod.rs, src/spec.rs, web/src/datavzrd.js
This PR addresses the new feature of a multi-select filter widget from #602 and therefore also closes #602.
=> feat: Add new multi-select filter widgets for text columns with few values

templates/bar_plot.vl.tera
This PR fixes a problem in the bar plot template when there was no color definition present.
=> fix: Fix bar plot without color definition

src/render/portable/mod.rs, templates/data.js.tera, templates/table.html.tera
This PR refactors the report directory structure moving the data into its own directory. Data is also now contained in a single js file.
=> refactor: Restructure report directory

.examples/example-config.yaml, Cargo.lock, Cargo.toml, src/render/portable/mod.rs, templates/table.html.tera
Another performance update regarding the storage of datavzrd reports.
=> perf: Minify table html files

src/render/portable/mod.rs
This PR makes datavzrd actual use numeric json types for floats and integers. This is much nesscessary for future updates possibly using msgpack for better data compression.
=> perf: Use numeric json types

src/render/portable/mod.rs
A quick fix for an error introduced with #668.
=> fix: Change integer type to fix possible overflow error

src/spec.rs
This PR skips the unnecessary config validation step or optional columns.
=> fix: Skip validations for non-present optional columns

src/render/portable/mod.rs
This PR fixes an issue where heatmaps were missing the pre-calculated domain which caused wrong colorization etc.
=> fix: Fix heatmap domain retrieval

README.md
A quick PR to update the docs with a contribution statement.
=> docs: Update README.md with contributing statement

src/render/portable/plot.rs, templates/table.html.tera
A quick PR to reduce html file size.
=> refactor: Reduce plot imports by merging plot specs into single javascript file

static/datavzrd.css, templates/table.html.tera
This PR removes all inline styles in order to reduce the file size of the html files
=> refactor: Remove inline styles

web/src/datavzrd.js, web/src/page.js, web/style/datavzrd.css
This PR allows hiding columns for in-memory-reports.
=> feat: Allow hiding columns for in-memory-reports

Cargo.toml
This should hopefully improve the performance and reduce runtime on bigger datasets.
=> perf: Use better link time optimization on release profile

web/src/datavzrd.js
=> fix: Fix last column hidden on exported svg and adjust header height to eventual label

web/src/datavzrd.js, web/src/page.js
Rewrote the eventListeners as in explained in the review.
=> refactor: Event Listeners and Functions

Cargo.lock, Cargo.toml, src/spec.rs
This massively improves the error messages by adding additional context of the configuration file to the error message.
=> feat: Improve context of error messages with format_serde_error

web/src/datavzrd.js
Unsorts the table after you sort the table with the button, If you click for the 2. time at the Sort button in unsorts.
=> feat: Allow unsorting tables

web/src/datavzrd.js
This PR fixes some bad interaction with additional headers caused by the recent introduction of the line numbers feature.
=> fix: Fix additional header row offset

src/spec.rs
This PR increases the maximum in memory rows to 20000.
=> refactor: Increase maximum in memory rows to 20000

templates/table.html.tera
Quick fix that removes an import
=> fix: Remove unused import

web/src/page.js, web/style/datavzrd.css
A quick PR to improve the usage of available page space for plot views.
=> fix: Improve plot controls and container size

src/render/portable/mod.rs, src/spec.rs, templates/img.html.tera, web/style/datavzrd.css
This PR adds a new `render-img` option as discussed in #789 and therefore also fixes #789.
=> feat: Add render-img option

Cargo.lock, Cargo.toml, src/render/portable/mod.rs
A quick PR fixing the missing excel headers.
=> fix: Fix missing headers in exported excel file

src/render/portable/mod.rs
This PR adds the missing data function for custom plot usage within add-columns.
=> fix: Fix missing data function for custom plot usage within add-columns

src/render/portable/mod.rs, web/src/datavzrd.js
This PR fixes an issue when a column name was containing single quotes. Thanks for reporting @btemoshir
=> fix: Fix bug when columns containing single quotes

web/src/datavzrd.js, web/style/datavzrd.css
This PR fixes an issue where the multi linkout dropdown was not showing properly in the SVG export.
=> fix: Multi linkout dropdown not showing properly in SVG export

templates/index.html.tera, tests/expected/index.html
This PR allows redirecting to specific views via URL parameter from reports index file in the following way:
```
path/to/report/index.html?view=movies
```
=> feat: Allow redirecting to specific views via URL parameter from reports index file

web/src/datavzrd.js
=> fix: Make in-memory search case-insensitive

src/render/portable/mod.rs, src/spec.rs, web/src/datavzrd.js
This pull request introduces support for a new `pinned` column state in the rendering configuration. This allows columns to be excluded from the multi-select column filter.
=> feat: Add new display-mode for pinned columns

src/spells.rs
This pull request introduces a caching mechanism for fetched spells to improve performance and reduce redundant network requests. The key changes include the addition of a `Mutex`-protected cache, modifications to the `fetch_spell` function to utilize this cache, and a new unit test to validate the caching behavior.
=> perf: Add caching for fetched spells using a Mutex-protected HashMap

src/spec.rs, web/src/datavzrd.js
This pull request introduces improvements to data handling and rendering logic in both the Rust backend and the JavaScript frontend. The key changes include optimizing record processing in datasets and enhancing heatmap configuration in the UI to support dynamic domain calculations.
=> fix: Allow legend definition for header definitions

web/src/datavzrd.js
This PR enables multiple sort in bootstrap table and updates the sort function to handle multiple columns and orders properly.
=> feat: Add multiple sort support
