README.md, src/render/portable/mod.rs, src/render/portable/plot.rs, src/spec.rs, templates/table.js.tera
This PR introduces a new keyword `header-rows` to datavzrd that allows the user to have multiple header rows per table.
=> feat: Allow multiple header rows

README.md, src/render/portable/mod.rs, src/spec.rs, static/datavzrd.css, templates/table.js.tera
This PR implements functionality to the `custom-plot` keyword that renders custom vega-lite plots into individual cells.
=> feat: Support custom plots

README.md, src/spec.rs, templates/table.js.tera
This PR adds the new keyword `vega-controls` to custom plots that turns vega-embed-controls on or off.
=> feat: Add vega-controls option

README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.html.tera
This PR introduces a new keyword `name` that allows the user to optionally set a name for the generated report that will be heading all resulting tables and plots.
=> feat: Add optional report name

README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
Add `pin-columns` keyword that lets the user fix columns to the left side of the table that will therefore be always visible.
=> feat: Add pin-columns keyword

README.md, src/render/portable/mod.rs, src/render/portable/utils.rs, src/spec.rs
This PR does some refactoring on the config specs. `items` is now split into `datasets` and `views`.
=> refactor: Separate views and datasets

src/render/portable/mod.rs
This PR fixes the wrong `column` value for the `TableLinkingError::NotFound` error.
=> fix: Display correct column on missing value

src/main.rs
This PR lets datavzrd create the given output directory if it doesn't exist.
=> feat: Create output directory if it does not exist

.examples/example-config.yaml, static/datavzrd.css, templates/plot.html.tera
This PR allows the user to use `"width": "container"` in their vega-lite specs and centers smaller plots horizontally and vertically.
=> feat: Allow user to use width: container in vega-lite specs

.examples/example-config.yaml, README.md, src/spec.rs, templates/table.js.tera
This PR renames `schema` to `spec` and `scheme` to `color-scheme` in the datavzrd config.
=> refactor!: Rename schema to spec and scheme to color-scheme

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
This PR adds a new keyword `domain` for `ticks` and `heatmap` that allows the user to define domains themselves.
=> feat: Add domain keyword for ticks and heatmap

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/spec.rs
This PR adds the keyword `optional` to columns defined in `render-table` that allows the user to have a column specified in `render-table` that is actually not present.
=> feat: Add optional keyword for render-table

.examples/example-config.yaml, .examples/specs/movies.vl.json, .examples/specs/oscars.vl.json, README.md, src/render/portable/mod.rs, src/spec.rs
This PR introduces a new keyword `spec-path` that allows the user to have their Vega-Lite specs in separate files cleaning up bigger config files.
=> feat: New keyword spec-path

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/spec.rs
This PR refactors `item` to `view`.
=> refactor!: Refactor item to view

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, templates/table.js.tera
This PR makes the entire row available for use in `link-to-url`. This makes something like this possible:
```yaml
render-table:
name:
link-to-url: "https://lmgtfy.app/?q=Is {name} in {movie}?"
```
with a csv file looking like this:
|name|movie|
|-----|------|
|Samuel L. Jackson|Pulp Fiction|
|Ryan Reynolds|Deadpool|
=> feat: Make entire row available to link-to-url

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/spec.rs, static/datavzrd.css, templates/table.js.tera
This PR implements a new keyword `display-mode` that allows user to see specified columns only in [detail view](https://examples.bootstrap-table.com/#options/detail-view.html#view-source).
=> feat: New keyword display-mode

.examples/specs/movies.vl.json, .examples/specs/oscars.vl.json, templates/plot.html.tera
This PR makes datavzrd not require `data` i.e. 
```json
"data": { "values": [] }
```
for plots anymore. Right now plots without defined `data` will not show properly. @FelixMoelder discovered this and we thought it might make sense to not require it.
=> fix: Do not require empty data for plots

.examples/specs/oscars.vl.json
Just a quick fix of the example config that had the wrong linkout in the oscar-plot spec.
=> fix: Fix example config

src/render/portable/mod.rs
This PR fixes #35. There was still a problem with empty csv files that had linkouts defined.
=> fix: Fix empty files with linkouts

static/datavzrd.css, templates/table.js.tera
This PR prevents cells with numbers having line breaks by adding `white-space: nowrap`.
=> fix: No linebreaks in numeric cells

static/datavzrd.css
This PR changes the highlighting of linked rows so it doesn't interfere with heatmaps.
=> fix: Highlight rows with border so it doesn't interfere with heatmaps

src/spec.rs
Just a quick PR that updates the doc string of `preprocess_columns`.
=> docs: Update preprocess_columns doc string

templates/table.js.tera
This PR fixes a problem where columns with `display-mode: detail` were not accessible from `link-url`.
=> fix: Missing columns when in detail mode for link-url

.examples/example-config.yaml, README.md, src/render/portable/utils.rs, src/spec.rs
This PR introduces a new keyword `default-view` that allows the user to specify a view that is shown when opening the index file.
=> feat: Add default-view keyword

templates/table.js.tera
This PR makes datavzrd not show plots generated with `ticks` that do not have any value. Vega-Lite plots look like this which could be somehow confusing as discovered by @FelixMoelder:
Alternatively to not showing a plot at all we could also have an empty plot (i.e only the horizontal line). What do you think @johanneskoester? 
**Option A** *(No plot at all)*:
**Option B** *(Empty plot)*:
=> fix: Do not show empty tick plots

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
This PR adds keyword `ellipsis` to datavzrd that allows the user to limit values in tables to the first *n* characters.
Example:
```yaml
views:
table-a:
dataset: my-dataset
render-table:
column-with-long-values:
ellipsis: 30 # only shows the first 30 characters with the rest accessible via a popover
```
=> feat: Add ellipsis keyword

README.md, src/render/portable/mod.rs, src/spec.rs
This PR adds a new keyword `hidden` that allows users to hide specific views and only access them via linkouts.
=> feat: Add new keyword hidden

README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
This PR removes the keyword `pin-columns` due a problem with bootstrap-table.
=> fix!: Remove pin-columns keyword

src/spec.rs
This PR allows datavzrd configs with `ellipsis` and `heatmap` both used together for the same column.
=> feat: Allow combining ellipsis with heatmap

README.md, src/render/portable/mod.rs, src/spec.rs
This PR allows missing values in other tables with keyword `optional`. This should solve the problem we talked about @FelixMoelder ☺️
=> feat: Allow missing values in other tables with keyword optional

.examples/data/movies.csv
Just a small fix for the example movie dataset that should fix that the year column is not detected as numeric.
=> docs: Fix example dataset

templates/table.js.tera
This PR removes linkouts from table if they do not exist. Beforehand an empty column with `-` was shown.
=> fix: Remove linkouts from table if non-existent

README.md, src/render/portable/mod.rs, src/spec.rs
This PR introduces a new keyword `aux-domain-columns` that allows to specify a list of other columns that will be additionally used to determine the domain of the tick plot and therefore closes #102.
=> feat: New keyword aux-domain-columns

src/spec.rs
Just a quick PR to please clippy by using the Default derive on AuxDomainColumns.
=> fix: Use derive for default implementation of AuxDomainColumns

.examples/example-config.yaml, src/render/portable/mod.rs, templates/table.js.tera
This PR makes datavzrd use the tick domain for filter brushes if present.
=> fix: Use tick domain for filter brush if present

src/render/portable/mod.rs
This PR makes datavzrd use existing heatmap domains for filter brushes.
=> fix: Include heatmap domains for filter brushes

src/render/portable/mod.rs, templates/table.js.tera
This PR adjusts datavzrds filter brush domains according to given values in `aux-domain-columns` columns.
=> fix: Include aux domains in filter brush domain

src/render/portable/mod.rs
This PR prevents panicking in case of `render-table` definitions for non-existent columns.
=> fix: Prevent panic in case of render-table definitions for non-existent columns

templates/table.js.tera
This PR makes the brush-filters slightly higher so the given space is used better. It also changes the color to a much brighter blue so the highlighted ticks have a much better visibility. This closes #133
=> feat: Improve brush-filters

README.md, src/render/portable/mod.rs
This PR allows using the `aux-domain-columns` keyword for non-numeric column heatmaps. Therefore this closes #132.
=> feat: Allow aux-domain-columns for non-numeric column heatmaps

static/datavzrd.css
This PR fixes #144 by adding a known workaround for [a well-known firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=688556) that overwrites borders with the background color.
=> fix: Fix column highlighting for firefox

.examples/example-config.yaml, templates/table.js.tera
This PR makes datavzrd show tick plots and heatmaps in columns with `display-mode: detail` and therefore closes #149.
=> feat: Show tick plots and heatmaps in display-mode: detail

templates/table.js.tera
This PR fixes an undesired behavior in datavzrd discovered by @FelixMoelder where custom plots in detail mode got overwritten with tick plots.
=> fix: Fix custom plots in detail mode

README.md, src/render/portable/mod.rs, src/spec.rs, templates/plot.html.tera
This PR allows datavzrd users to use multiple datasets in vega-lite plots of render-plot views like so:
```yaml
datasets:
my-data:
path: path/to/my-data.csv
my-other-data:
path: path/to/my-data.csv
views:
my-view:
datasets:
dataset-1: my-data
dataset-2: my-other-data
render-plot:
spec: |
{
"$schema": "https://vega.github.io/schema/vega-lite/v5.json",
"layer": [
{"data": {"name": "dataset-1", ...}}, 
{"data": {"name": "dataset-2"}, ...}]
}
```
=> feat: Support multiple datasets for render-plot views

src/render/portable/mod.rs
This PR only adds the `+` sign to the beginning of the table rows if columns with `display-mode: detail` exist and therefore fixes #157 by removing the `+` for the table when only columns with `display-mode: hidden` or `display-mode: normal` exist.
=> fix: Remove detail view when columns are hidden

src/main.rs
As the title suggests this PR makes datavzrd output warnings to stderr instead of stdout.
=> refactor: Output warnings to stderr instead of stdout

README.md, src/render/portable/mod.rs, src/render/portable/utils.rs, src/spec.rs, templates/html.html.tera
This PR adds new render-html keyword and allows integration of aux-libraries as described in #161 and therefore closes #161.
=> feat: Add new render-html keyword and allow integration of aux-libraries

src/render/portable/plot.rs
Just a quick PR that shows empty values of columns as `NA` in the corresponding histogram.
=> fix: Show empty values in separate category in histograms

README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
This PR allows the user to customize the value that will be used for a heatmap with the new keyword `custom-content` and therefore closes #170.
=> feat: Allow rendering custom content into any heatmap cell

README.md, src/render/portable/mod.rs, src/spec.rs, templates/table.js.tera
This PR does some refactoring regarding the newly added `additional-headers` keyword.
=> feat!: rename header-rows setting into headers

src/utils/column_type.rs
Just some quick refactoring removing an earlier todo regarding the default implementation for an enum.
=> refactor: Use derive for default implementation of enum

src/utils/column_type.rs
This PR fixes the behavior of classifying columns when empty values occur.
=> fix: Fix column classification for NA values

src/render/portable/plot.rs
This PR fixes the possible entering of unreachable code when data contains empty columns by treating empty columns like they were of the type `String`. This bug was probably introduced when #206 changed the overall behavior of empty values in datasets.
=> fix: Fix entering of unreachable code when data contains empty columns

templates/table.js.tera
This PR fixes the brush filter domains for columns that have a domain with more than two values i.e numeric heatmap definitions where `range` is used.
=> fix: Fix brush filter domain for numeric heatmap plots

Cargo.lock, Cargo.toml, src/render/portable/mod.rs, src/render/portable/plot.rs, src/render/portable/utils.rs
This PR uses `minify_js` to minify rendered js files before writing. This should reduce file sizes slightly.
I probably haven't caught all places js files are written, feel free to add any that I missed ;)
(It may also be interesting to minify the html files, haven't looked into that, yet)
=> feat: Add minify_js to decrease file sizes

README.md, src/spec.rs, templates/table.js.tera
This PR adds a new option `clamp` to heatmaps allowing the user to set the behavior for continuous scales.
=> feat: Add new heatmap option clamp

templates/table_heatmap.js.tera
This PR fixes some minor styling issues with the recently added heat map export function.
=> fix: Align text marks of heatmap table

src/render/portable/mod.rs, templates/table_heatmap.js.tera
This PR merges two or more legends if the columns share the same domain (including aux-domains) and the columns are neighboured. This makes the plot-view much more compact for some use-cases.
=> feat: Merge legends when domains are equal

templates/table.js.tera
This PR fixes the behavior of `precision` for `0.0` and negative values that were missing a `Math.abs()`.
=> fix: Fix precision behaviour for zero and negative values

src/render/portable/mod.rs
This PR adds a context when there is a problem with parsing a numeric domain in a heatmap.
=> fix: Add context to error when parsing numeric domain

src/render/portable/mod.rs, src/utils/column_type.rs
This PR fixes a problem where empty columns were falsely classified as numeric.
=> fix: Fix wrong classification of empty columns

static/datavzrd.css
This PR adds `white-space: nowrap;` to table cells so they don't overlap each other in a weird way.
=> fix: Fix overlapping fonts by removing line breaks

src/render/portable/mod.rs, src/spec.rs
This PR changes scale types and multiple other types to an enum and therefore closes #254.
=> refactor: Change scale types etc. to enum

src/render/portable/mod.rs
This PR fixes #253 by defaulting a columns width to 0 when there is no data to show.
=> fix: Fix error when rendering empty multi header files

src/render/portable/plot.rs, src/utils/column_type.rs, templates/table.js.tera
This PR optimizes datavzrds recognition of `NA` values. `&str` now implement an `isNa` trait for easier further future modification if needed. This also fixes a small bug with the filter brush plot that occurred with `NA` values.
=> feat: Optimize NA value recognition

static/datavzrd.js
A quick PR that fixes wrongly displayed data values in tick and bar plots.
=> fix: Fix wrong data values for tick and bar plots

src/render/portable/mod.rs, templates/table_heatmap.js.tera
This PR quickly adds the `clamp` option to the heatmap plot.
=> fix: Add missing clamp parameter to heatmap plot

README.md
Since we moved datavzrd into its own org the links should be updated as well.
=> docs: Update repository link in badge

src/render/portable/mod.rs, src/render/portable/plot.rs, src/utils/column_type.rs
This PR fixes some problems with the column classification when the given table had multiple header rows that were falsely used to classify the columns type.
=> fix: Fix column classification for tables with additional header rows

.examples/example-config.yaml
Just a quick PR that changes the color-scheme of column `Rated` from `accent` to `tableau20` due to `accent` only providing 8 different color values while the domain of  `Rated` has more than 8 different values.
=> docs: Fix color-scheme of view movies

src/spec.rs
This PR fixes an error with clamped scales during the config validation.
=> fix: Remove validation error when values exceed given domain and clamp is set to true

templates/table.js.tera
This PR fixes the out of position headers when a dataset had additional headers and no label was defined and the view didn't have any columns with `display-mode: detail`.
=> fix: Fix headers for views without detail mode and no header labels

README.md, src/render/portable/mod.rs, src/spec.rs, static/datavzrd.js, templates/table.js.tera
This PR adds the already for columns existing keyword `ellipsis` to header definitions as well allowing to shorten values to the first n characters with the full content displayed as a popover on hover.
=> feat: Add ellipsis option for header definitions

src/render/portable/mod.rs, templates/plot.html.tera
This PR fixes #292 by also storing the plot data in a compressed version.
=> perf: Compress data for plot views with lz-string

src/render/portable/mod.rs, src/render/portable/plot.rs, src/render/portable/utils.rs
This PR fixes a problem where values of tick or bar plots would be located outside of the domain due to issues with the precision keyword in combination with the domain calculation.
=> fix: Round domains according to precision

src/render/portable/mod.rs
This PR fixes #316. This should reduce the storage space significantly.
=> perf: Remove html search pages for views that don't use them

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/render/portable/utils.rs, src/spec.rs, templates/table.js.tera
This PR closes #328 by adding a `webview-controls` option to the config that is turned off by default.
=> fix: Turn off webview controls by default

templates/table.js.tera
A quick fix that adds a missing `,`.
=> fix: Fix js for multiple header ellipsis usage

templates/table.js.tera
This PR fixes a small problem where filter brushes weren't applied if they're dragged outside of the plot. This PR fixes this by adding another event that triggers the filer.
=> fix: Fix non-working filter if brush is dragged outside of plot

templates/table.js.tera
This PR removes the `beforeprint` event entirely in favor of the Vega plot view.
=> feat: Remove print option in favour of vega plot view

Cargo.toml
The newest  version of minify-js seems to create some problems: 
Version 0.5.2 seems to work fine.
=> build(deps): Pin minify-js to 0.5.2

src/spec.rs, static/datavzrd.js
This PR makes datavzrd pre-calculate the heat map domain if it's numerical. Beforehand configs like the following were not working since the domain needs to be specified for vega:
```yaml
plot:
heatmap:
scale: linear
range:
- white
- "#186904" 
```
=> fix: Pre-calculate numeric heatmap domain

static/datavzrd.js, templates/table.html.tera
Apparently, in old browsers, using just `target="_blank"` to open a web page in a new tab gives access to some parts of the originating tab. See this link for an up to date account of the problem:
https://mathiasbynens.github.io/rel-noopener/
TL;DR: [Just also add ` rel="noopener noreferrer"` to be on the safe side](https://stackoverflow.com/a/17711167/2352071)
Or if you actually need exactly that behaviour (in newer browsers that changed the default), use `rel="opener"`. With regard to this: I am not sure about the change in the template file. Maybe that behavior is somehow wanted there?
=> fix: `<a target="_blank">` security vulnerability

src/render/portable/mod.rs
This PR should fix a missing empty report file when dataset with multiple header rows is empty.
=> fix: Render missing empty report when dataset with multiple header rows is empty

src/spec.rs
This PR stops datavzrd from doing any unnecessary preprocessing of configurations for views with empty datasets. This caused a bug for quantitative heatmap definitions since datavzrd could not automatically recognize the domain due to the empty dataset. It should of course also increase the performance slightly.
=> fix: Skip preprocessing when dataset is empty

Cargo.lock, Cargo.toml, src/spec.rs
This PR makes datavzrd use the `fancy-regex` crate instead of the previously used `regex` crate. This allows using something like [negative look-ahead or other features](https://docs.rs/fancy-regex/latest/fancy_regex/#syntax).
=> feat: migrate to fancy-regex for regex evaluation (e.g. enabling negative look-ahead/around)

static/datavzrd.js
This PR fixes a problem where hovering over the brush plots re-renders the plot.
=> fix: Remove re-rendering when mouse leaves brush filter unpressed

static/datavzrd.js
This PR fixes a problem where table headers were not shown when the table has additional headers.
=> fix: Fix hidden table headers when table has additional headers

src/render/portable/mod.rs
This PR fixes the page calculation for a specific corner case where the number of rows was an exact multiple of the page size.
=> fix: Fix page calculation

web/src/datavzrd.js
This PR follows #457 which didn't seem to fully solve the problem.
=> fix: Show missing table headers

src/render/portable/mod.rs, web/src/datavzrd.js
This PR fixes the false implementation of `custom-content` for heatmap definitions. It also moves the custom javascript function into the appropriate `functions.js` file which also adds the proper error handling we introduced lately. Also this PR fixes some problems with all sorts of plots when the column definition includes `display-mode: detail`.
=> fix: Fix custom-content for heatmap definitions

web/src/datavzrd.js
A quick PR that adds a missing export for a js function.
=> fix: Export embed_search function

templates/html.html.tera, templates/plot.html.tera, templates/table.html.tera
This PR fixes a problem where the view dropdown menu was placed to far left due to a long view title.
=> fix: Fix possibly misplaced view dropdown for very long titles

.github/workflows/release-please.yml
Seems like this was still missing as seen in the last runs error message.
=> ci: Add git user and email to update webview job

web/src/datavzrd.js
This PR allows the user to use `custom` or `custom-path` with `display-mode: detail` and therefore fixes #527.
=> feat: Allow custom or custom-path usage with display-mode: detail

.github/workflows/release-please.yml
A quick PR that should finally fix the update of the webview by giving the commit and push job a token that lets it update the view repository.
=> ci: Fix update webview job

src/render/portable/mod.rs, templates/empty.html.tera, templates/html.html.tera, templates/plot.html.tera, templates/table.html.tera
This PR makes datavzrd only show the row count badge if the view is either empty or it is a table view. Row counts for plot or html views could be confusing for the user.
=> fix: Show row count badge only for table views

templates/table.html.tera
Just a quick PR that fixes a small issue where the word `rows` was duplicated in the menu after #535.
=> fix: Remove duplicated word rows

.examples/example-config.yaml, README.md, src/render/portable/mod.rs, src/spec.rs, templates/bar_plot.vl.tera, templates/tick_plot.vl.tera
This PR allows to define color mappings for tick and bar plots like the following one:
```yaml
imdbRating:
precision: 1
plot:
bars:
scale: linear
domain:
- 1
- 10
color:
scale: linear
range:
- red
- green
```
This PR closes #586.
=> feat: Add color option to tick and bar plots

templates/table.html.tera, web/src/datavzrd.js
This PR makes datavzrd pad the description height of the table in case it is smaller than one third of the window height.
=> feat: Add padding to description if it is small

src/spec.rs
This PR implements a word color mapping to datavzrd that makes written colors like `red` or `green` use the according vega-lite colors from the category20 scheme.
=> feat: Preprocess color words for more aesthetic colors

src/render/portable/mod.rs, src/spec.rs
This PR does some minor refactoring and adds a test case for the `is_empty()` method of the DatasetSpec struct and therefore should fix #417 for now.
=> refactor: Use dataset functions instead of explicitly generating new reader

build.rs
This PR fixes a problem when copying the web directory within the build script that caused problems when recompiling datavzrd. It also manually tells cargo to rebuild only if the web directory changed.
=> build: Improve and fix build script

build.rs
This PR fixes a build problem on OS X.
=> build: Fix web path causing build problems on OS X

src/render/portable/mod.rs, templates/search_dialog.html.tera, web/src/datavzrd.js
This PR should highly improve report storage use with using lz-string compression on the search dialog data and therefore closes #628.
=> perf: Use lz-string compression for search dialogs

src/render/portable/mod.rs, src/spec.rs
This PR should prevent bugs like #634 by validating all outputted json for tick and bar plots is valid JSON.
=> test: Add JSON spec validation for tick and bar plots

templates/table.html.tera, web/src/datavzrd.js
This PR should massively improve report storage by reducing the number of modals used to display histograms to 1 instead of of the number of displayed columns. For the test report this reduces the size of each html page from `20kb` to `11kb`.
=> perf: Use single modal for histograms of all columns

Cargo.lock, Cargo.toml, src/render/portable/mod.rs, src/utils/compress.rs, src/utils/mod.rs, web/src/datavzrd.js
This PR adds JSONM compression that somehow wasn't used. All compression is now outsourced into separate functions for Rust as well as for the javascript library.
=> perf: Use JSONM for compression

src/render/portable/mod.rs
This PR removes the minifying of the custom javascript functions given by users in order to prevent problems with minify-js like this https://github.com/wilsonzlin/minify-js/issues/21
=> fix: Dont minify custom javascript functions

.examples/example-config.yaml, web/src/datavzrd.js
This PR fixes a bug where labels where ignored when used together with `display-mode: detail`.
=> fix: Display labels with display-mode: detail

web/src/page.js
This PR fixes an issue where `null` was being displayed as the description if there was none.
=> fix: Remove null being displayed when table doesnt have a description

Cargo.lock, Cargo.toml, build.rs
This should remove any os specific problems occurring with `cp`.
=> build: Remove os specific parts from build script

web/src/datavzrd.js
Just a quick PR deactivating the recently added resizing for composite plots.
=> fix: Deactivate plot view resize controls for composite plots

web/style/datavzrd.css
This PR addresses an issue with the filter widget where the tooltip of the brush filter for numeric values was behind the filter widget.
=> fix: Fix popover z-index for numeric search widget

src/render/portable/mod.rs
This PR fixes an issue where the unfold option was not present when only a column added via `add-columns` was using `display-mode: detail`.
=> fix: Fix missing unfold option when only add-column uses display-mode detail

src/spec.rs
Just a small PR to allow using `nominal` as a scale type that will internally then be aliased to the actual existing `ordinal` vega scale type. Should make writing configurations slightly easier.
=> fix: Allow use of nominal for scale type

src/render/portable/mod.rs, src/spec.rs, src/spells.rs
This PR improves the behaviour for further configuring spells. For example: `display-mode: detail` was previously overwritten by by a spell even if not set explicitly due to defaults. This is now fixed by setting defaults later in the preprocessing of columns.
=> fix: Improve behaviour for further configuring spells

Cargo.lock, Cargo.toml, src/cli.rs, src/main.rs, src/spec.rs, src/spells.rs, src/suggest.rs
This pull request introduces a new feature for suggesting configuration files based on input files.
* Added a new `Suggest` command to the CLI for generating configuration files from tabular input files. This includes handling input files and separators, and generating a configuration report.
=> feat: Add new subcommand for suggesting configurations based on files

src/spec.rs
This pull request simplifies the serde attribute usage in the `src/spec.rs` file by removing the unnecessary `deserialize` parameter from the `rename_all` attribute. This change ensures consistency and reduces redundancy across multiple struct definitions.
Fixes #864
=> fix: Fix wrong case for configs generated with datavzrd suggest

src/utils/column_type.rs
This pull request includes a few changes to the `src/utils/column_type.rs` file to improve logging and handle specific cases where values contain commas. The most important changes include adding a new import for the `log::warn` function and modifying the `impl ColumnType` to log a warning when a potential float value containing a comma is encountered.
=> feat: Add warning for potential floats using comma

.examples/example-config.yaml, src/render/portable/mod.rs, src/spec.rs, src/spells.rs, src/suggest.rs, web/src/datavzrd.js
This PR adds a new `pills` option for heatmap like visualizations for cells containing multiple values split by a delimiter like `,`.
=> feat: Add new pills keyword

.examples/example-config.yaml, src/spec.rs, web/src/datavzrd.js
The logic for `renderPill` is similar to the existing logic in `shortenColumn`. However, the pills require different wrapping elements, so it was easier to duplicate some of this logic than to try and unify these utilities.
The new logic also supports pills with `ellipsis === 0`, in which case the pills are rendered as circles without any text content, and the pill value is shown in a tooltip on hover.
fixes #880
=> feat: Support the `ellipsis` setting on pill plots.

src/cli.rs, src/main.rs, src/publish.rs
This pull request introduces a new feature to specify an entry point for the report in the `publish` command. The changes primarily involve adding an optional `entry` parameter to various structs and methods, and implementing logic to handle this new parameter. Fixes #874 
* [`src/cli.rs`](diffhunk://#diff-b2812f19576dd53d0c35b107a322f58a00fce6977f4b5976e1961853982af3ccR61-R64): Added an optional `entry` parameter to the `publish` command in the `Command` enum.
* [`src/main.rs`](diffhunk://#diff-42cb6807ad74b3e201c5a7ca98b911c5fa08380e942be6e4ac5807f8377f87fcR37-R39): Updated the `publish` command handling to pass the new `entry` parameter to the `Repository` struct.
* `src/publish.rs`: 
* Added an `entry` field to the `Repository` struct and updated the `new` method to accept this …
=> feat: Add --entry option for datavzrd publish command

web/package.json, web/src/datavzrd.js
This pull request includes several changes to the `web` package to replace the `dom-to-svg` library with `html-to-image` and improve the handling of SVG downloads. Additionally, it includes minor improvements to HTML attributes. The most important changes are as follows:
* [`web/package.json`](diffhunk://#diff-b861012a5dd72b8a9f3281b7cf09f5a779c98569d040b1bbc1db50f1b15e7cceL25-R25): Replaced the `dom-to-svg` library with `html-to-image` for better SVG handling.
* [`web/src/datavzrd.js`](diffhunk://#diff-ff7315eccecc4e262837c3fcc7c3e46882ee07f19502b96aa6010a63b74d3ff2L13-R13): Updated import statement to use `html-to-image` instead of `dom-to-svg`.
* [`web/src/datavzrd.js`](diffhunk://#diff-ff7315eccecc4e262837c3fcc7c3e46882ee07f19502b96aa6010a63b74d3ff2L1439-R1440): Removed …
=> fix: Replace dom-to-svg with html-to-image for SVG downloads

web/src/datavzrd.js, web/style/datavzrd.css
This pull request includes changes to the `web/src/datavzrd.js` and `web/style/datavzrd.css` files to improve the behavior and appearance of popovers in the application. The most important changes include updating the event listener for popover activation and adjusting the z-index of popovers to ensure they appear above other elements.
Popover behavior improvements:
* [`web/src/datavzrd.js`](diffhunk://#diff-ff7315eccecc4e262837c3fcc7c3e46882ee07f19502b96aa6010a63b74d3ff2L1128-R1128): Changed the event listener from `'click'` to `'shown.bs.popover'` for the popover activation to ensure proper handling of checkbox filters within the popover.
* [`web/src/datavzrd.js`](diffhunk://#diff-ff7315eccecc4e262837c3fcc7c3e46882ee07f19502b96aa6010a63b74d3ff2L1155-R1155): Updated the event listener …
=> fix: Update popover event handling and increase z-index for better visibility

web/package.json, web/src/datavzrd.js
A few bugfixes regarding the recently introduced column filtering. This also updates `bootstrap-table` to the latest version.
=> fix: Fix unhidden columns after page change or sorting

src/spec.rs, web/src/datavzrd.js
This PR introduces a new keyword `merge` to `pills` that allows to ommit the padding between pills and merge them into one. This should save some space when many values are present in a single cell. Example usage:
```yaml
Genre:
plot:
pills:
color-scheme: category20
ellipsis: 0
merge: true
```
resulting in:
=> feat: Add support for merged pill rendering

src/spec.rs
This pull request makes improvements to error handling in the `ItemsSpec` implementation within `src/spec.rs`. Specifically, it adds a new error case to handle missing dataset properties.
=> fix: Improve error message for views with missing dataset

src/spec.rs
This pull request introduces a validation mechanism to ensure that configuration files are not empty, improving the robustness of the application when handling configuration inputs - and therefore fixes #984.
=> fix: Improve error for empty config files

src/utils/column_type.rs
This pull request updates the `ColumnType` utility in `src/utils/column_type.rs` to improve the clarity of warning messages by including the column name in the output. The changes primarily affect the `update` method and its usage across the codebase.
* [`src/utils/column_type.rs`](diffhunk://#diff-ec53979c9d86ff52a38afa89678074aebf9b0cad8b15ff078b41c8c2d5c057a0L18-R18): Modified the `update` method in `ColumnType` to accept an additional `column` parameter, allowing warning messages to specify the column name.
* [`src/utils/column_type.rs`](diffhunk://#diff-ec53979c9d86ff52a38afa89678074aebf9b0cad8b15ff078b41c8c2d5c057a0L35-R35): Updated the warning message in the `update` method to include the column name, enhancing the context for users encountering float-related parsing issues.
* …
=> fix: Add column name to float warning message

web/src/datavzrd.js
This pull request improves the readability of table cells and detail cards in the data visualization UI by dynamically adjusting text color for better contrast against background colors. The main enhancement is the addition of logic to detect dark backgrounds and automatically switch text color to white, ensuring accessibility and clarity.
=> fix: Set text color to white on dark heatmap backgrounds

.github/workflows/apply-clippy-lints.yaml, .github/workflows/example-report-on-pr.yml, .github/workflows/example-report.yml, .github/workflows/release-please.yml, .github/workflows/rust.yml
This pull request updates the way `pnpm` is installed across several GitHub Actions workflow files to use the official `pnpm/action-setup` action, specifying version 10, instead of installing it globally via `npm install -g pnpm`.
=> ci: Use pnpm setup action

.gitignore, Cargo.lock, Cargo.toml, src/spells.rs
- Update Rust dependencies to latest compatible versions - Switch from Python::with_gil to Python::attach in spells.rs for PyO3 0.26 compatibility - Add /out to .gitignore
=> chore(deps): Update dependencies, switch to Python::attach
